# Generated by Django 3.1.6 on 2021-10-23 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jrecomments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.IntegerField(default=1, primary_key=True, serialize=False, unique=True)),
                ('podcast', models.IntegerField(default=0)),
                ('popularity', models.IntegerField(default=0)),
                ('user', models.UUIDField()),
                ('comment', models.TextField()),
                ('datetime', models.DateTimeField()),
                ('likes', models.IntegerField(default=0)),
                ('dislikes', models.IntegerField(default=0)),
                ('parent_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='podcast',
            name='comments',
            field=models.BinaryField(default=None, null=True),
        ),
    ]
