# Generated by Django 3.1.6 on 2021-10-24 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jrecomments', '0003_auto_20211023_2341'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='podcast',
            name='duration',
            field=models.TextField(default='0h0m', null=True),
        ),
    ]
