# Generated by Django 3.1.6 on 2021-10-28 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jrecomments', '0005_auto_20211024_0133'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='replyToColor',
            field=models.TextField(default='(0,0,0)'),
        ),
        migrations.AddField(
            model_name='comment',
            name='replyToId',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comment',
            name='replyToName',
            field=models.TextField(default='Unknown Name'),
        ),
    ]
