# Generated by Django 3.1.6 on 2021-10-28 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jrecomments', '0006_auto_20211028_0048'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='sub_comments',
            field=models.BinaryField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='sub_count',
            field=models.IntegerField(default=0),
        ),
    ]
