# Generated by Django 3.1.6 on 2021-11-05 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jrecomments', '0007_auto_20211028_0505'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='popularity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='podcast',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
