# Generated by Django 3.1.6 on 2021-11-10 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jrecomments', '0011_userdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='datetime',
            new_name='date_time',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='dislikes',
            new_name='podcast_id',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='podcast',
            new_name='reply_id',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='name',
            new_name='reply_username',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='replyToName',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='donor',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='name_color',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='replyToColor',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='replyToId',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
    ]
