# Generated by Django 3.1.6 on 2021-11-11 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jrecomments', '0012_auto_20211110_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='youtube_links',
            field=models.BinaryField(default=None, null=True),
        ),
    ]
