# Generated by Django 3.1.6 on 2021-11-19 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jrecomments', '0013_podcast_youtube_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='comments',
            field=models.IntegerField(default=0),
        ),
    ]
