# Generated by Django 3.1.6 on 2021-11-20 07:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jrecomments', '0014_auto_20211119_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_offsite_comment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comment',
            name='yt_channel_id',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='comment',
            name='yt_comment_id',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='comment',
            name='yt_parent_id',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='comment',
            name='yt_video_id',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='podcast',
            name='last_yt_scrape',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='comment',
            name='reply_username',
            field=models.TextField(default=''),
        ),
    ]
