# Generated by Django 3.1.6 on 2021-12-02 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jrecomments', '0015_auto_20211120_0224'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='username',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='name',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='username',
            field=models.CharField(default='', max_length=80),
        ),
    ]
