# Generated by Django 3.1.6 on 2021-12-02 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jrecomments', '0017_auto_20211202_0542'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserData',
        ),
    ]
